version: "3"
services:
  ffvae:
    container_name: ffvae
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ffvae
    volumes:
      - .:/usr/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    shm_size: 2gb
