latent_dim: 50
res_dir: results
seed: 23
dataset: celeba
y: Smiling
s: Male
batch_size: 256
root: data/CelebA
n_sens: 1
lr: 0.0001
mlp_lr: 0.001
vae_epochs: 1
mlp_epochs: 100
target_sens: 0
alpha: 1000
gamma: 256
checkpoint_every: 25
no_cuda: False
